---
title: "human_DNT_preprocessing"
author: "Adam Pelletier"
date: "09/18/2020"
output: html_document
---

```{r setup, message = FALSE, warning=FALSE}
#### Load required packages for analysis
## Some packages may require installation from Bioconductor : "https://bioconductor.org/install/" 
suppressPackageStartupMessages(library(rstudioapi))
suppressPackageStartupMessages(library(rmarkdown))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(biomaRt))
suppressPackageStartupMessages(library(pvca))
suppressPackageStartupMessages(library(GGally))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(PCAtools))
suppressPackageStartupMessages(library(fgsea))
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(getwd())
```


```{r setup_vars}
inputDir <- "input"
outputDir <- "output"
figureDir <- "output/figures"
dataDir <- "output/data"

```



##load Data
```{r load_data}

count_mat_raw_prep <- do.call("rbind", lapply(list.files("input/counts", 
                                                         full.names = T), function(x){
          sample <- gsub("input/counts/", "", x)
          sample <- gsub("_counts_gene", "", sample)
          sample <- gsub("Sample_", "", sample)
          df <- read_tsv(x, col_names = F) %>%
                dplyr::rename(counts = 2,
                              ensID = 1) %>%
                mutate(sample = sample)
})) %>%
    spread(sample, counts, fill = 0) %>%
    filter(!grepl("^__",ensID)) %>%
    column_to_rownames("ensID") %>%
    as.matrix()

```


```{r get ensID}

ensembl <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
symbolConv <- getBM(attributes= c("ensembl_gene_id","hgnc_symbol", "description"),
                      filters = 'ensembl_gene_id', values =row.names(count_mat_raw_prep), mart = ensembl)



```



```{r pData}
# count_mat_raw_prep <- read_tsv(file = "input/summary_star_genes_readcount.stranded.annotated.tsv")  %>%
#                   as.data.frame() %>%
#                   filter(row_number() > 4) %>%
#                   mutate(ensembl_gene_id = gsub("[.].*", "", X1))

count_mat_raw <- count_mat_raw_prep %>%
            
            dplyr::select(c(pData$`sample name`, "ensembl_gene_id")) %>%
            column_to_rownames("ensembl_gene_id") %>%
            as.matrix()

pData <- data.frame('sample_name' = colnames(count_mat_raw_prep)) %>%
            separate('sample_name', into = c('cell_type', 'temp'), sep = "-R200-" , remove = F) %>%
            mutate(Donor = gsub("-C.*", "", temp))  %>%
  
            mutate(Culture = ifelse(nchar(gsub("-C", "", temp)) == nchar(temp),
                                    "Fresh", "Culture")) %>%
            mutate(condition = paste(cell_type, Culture, sep = "__")) %>%
            dplyr::select(-temp)
            

count_mat_raw <- count_mat_raw_prep %>%
            as.data.frame() %>%
            rownames_to_column("ensembl_gene_id") %>%
            gather(sample, value, -ensembl_gene_id)  %>%
            inner_join(., symbolConv, by = "ensembl_gene_id") %>%
            filter(hgnc_symbol != "") %>%
            group_by(hgnc_symbol, sample) %>%
            mutate(total_counts = sum(value)) %>%
            ungroup() %>%
            dplyr::select(hgnc_symbol, sample, total_counts) %>%
            unique() %>%
            spread(sample, total_counts) %>%
            column_to_rownames("hgnc_symbol") %>%
            as.matrix()
                  


```


```{r read_stats}

# 
# class_rename <-  read_tsv(file = "input/Pasquin_summary_star_genes_readcount.stranded.annotated (1).tsv")  %>%
#                   as.data.frame() %>%
#                   filter(row_number() <= 4) %>%
#                   dplyr::select(X1) %>%
#                   mutate(new_class = c("unaligned", "Multimapped","N_noFeature",   ))
#   

ReadStats <- read_tsv(file = "input/summary_star_genes_readcount.stranded.annotated.tsv")  %>%
                  as.data.frame() %>%
                  filter(row_number() <= 4) %>%
                  dplyr::select(c("X1", pData$`sample_name`)) %>%
                  column_to_rownames("X1")
                  

ReadStats_plot <- function(readstats, count_mat){
  df <- readstats %>%
        rownames_to_column("Class") %>%
        gather(SampleID, NumberReads, -Class) %>%
        spread(Class, NumberReads)
  
  Counted <- data.frame(counts = colSums(count_mat))
  
  plotDF <- df %>%
                mutate(exonic = Counted$counts[match(SampleID, 
									   											    table=rownames(Counted))],
							intronic_and_intergenic = N_noFeature,
              multiMap =  N_multimapping,
	      			unaligned = N_unmapped) %>%
              dplyr::select(SampleID, exonic,intronic_and_intergenic,unaligned, multiMap, N_ambiguous ) %>%
							mutate(TotalReads =  rowSums(dplyr::select(., -one_of(c("SampleID")))),
							Surviving = rowSums(dplyr::select(., one_of(c("exonic", "intronic_and_intergenic", "multiMap", "N_ambiguous")))),
							trimmed = TotalReads-Surviving) %>%
	# 						 %>%
	           dplyr::select(SampleID,
	           		 				exonic,
	           		 				intronic_and_intergenic,
	           		 				trimmed,
	           		 				multiMap,
	           		 				unaligned) %>%
	           gather(key, value, -SampleID) %>%
	           dplyr::rename(Class = key,
	           		 				   NumberReads = value) %>%
             group_by(SampleID) %>%
              mutate(total = sum(NumberReads)) %>%
              ungroup() %>%
              mutate(relReads = NumberReads / total) %>%
	           mutate(SampleID = as.factor(SampleID))
  
   plotDF_p <- plotDF %>%
               spread(Class, NumberReads) %>%
               mutate(TotalReads = rowSums(.[2:6])) %>%
               gather(Class, NumberReads, -SampleID,-TotalReads) %>%
               mutate(Read_prop = NumberReads / TotalReads) %>%
               dplyr::select(-NumberReads,-TotalReads) %>%
                     mutate(Class = factor(Class))
    rS <- ggplot(data    = plotDF,
             		 mapping = aes(x    = SampleID,
                           				 	  y    = NumberReads,
                           				 	  by   = Class,
                           					  fill = factor(Class))) +
         geom_bar(stat   = "identity", color = "black") +
      	 theme(axis.text.x      = element_text(angle=90, size=6),
           	   		axis.line        = element_line(color = "grey"),
               		panel.background = element_blank()) +
      	 scale_y_continuous(expand = c(0, 0)) +
      	 labs(x="SampleID")
      rS_rel <- ggplot(data    = plotDF,
             		 mapping = aes(x    = SampleID,
                           				 	  y    = relReads,
                           				 	  by   = Class,
                           					  fill = Class)) +
         geom_bar(stat   = "identity", color = "black") +
      	 theme(axis.text.x      = element_text(angle=90, size=6),
           	   		axis.line        = element_line(color = "grey"),
               		panel.background = element_blank()) +
      	 scale_y_continuous(expand = c(0, 0)) +
         ylab("Relative Frequency of reads") + 
      	 labs(x="SampleID")
    
    out <- list("absolute" = rS, "relative" = rS_rel)
}


ReadStats_plot_exonic <- function(count_mat, fData , categories = 5){
  df <- count_mat %>%
        as.data.frame() %>%
        rownames_to_column("GeneID") %>%
        gather(SampleID, NumberReads, -GeneID) %>%
        inner_join(., fData %>% rownames_to_column("GeneID"), by = "GeneID") %>%
        group_by(SampleID, Category) %>%
        summarise(sumReads = sum(NumberReads)) %>%
        ungroup() 
  allSamplesDF <- df %>%
        group_by(Category) %>%
        summarise(allSumReads = sum(sumReads)) %>%
        ungroup() %>%
        mutate(category_rank = rank(-allSumReads, ties.method = "first")) %>%
        mutate(category_collapse = ifelse(category_rank > categories, "Others", Category)) %>%
        dplyr::select(Category, category_collapse)
  
  plotDF <- df %>%
        inner_join(., allSamplesDF, by = "Category") %>%
        group_by(SampleID, category_collapse) %>%
        summarise(collapseReads = sum(sumReads)) %>%
        ungroup() %>%
        dplyr::rename(NumberReads = "collapseReads",
                      Category = "category_collapse") %>%
        group_by(SampleID) %>%
        mutate(total = sum(NumberReads)) %>%
        ungroup() %>%
        mutate(relReads = NumberReads / total) %>%
        mutate(Category = as.factor(Category)) 
  
  
    rS <- ggplot(data    = plotDF,
             		 mapping = aes(x    = SampleID,
                           				 	  y    = NumberReads,
                           				 	  by   = Category,
                           					  fill = Category)) +
         geom_bar(stat   = "identity", color = "black") +
      	 theme(axis.text.x      = element_text(angle=90, size=6),
           	   		axis.line        = element_line(color = "grey"),
               		panel.background = element_blank()) +
      	 scale_y_continuous(expand = c(0, 0)) +
      	 labs(x="SampleID")
    
    rS_rel <- ggplot(data    = plotDF,
             		 mapping = aes(x    = SampleID,
                           				 	  y    = relReads,
                           				 	  by   = Category,
                           					  fill = Category)) +
         geom_bar(stat   = "identity", color = "black") +
      	 theme(axis.text.x      = element_text(angle=90, size=6),
           	   		axis.line        = element_line(color = "grey"),
               		panel.background = element_blank()) +
      	 scale_y_continuous(expand = c(0, 0)) +
         ylab("Relative Frequency of reads") + 
      	 labs(x="SampleID")
    
    out <- list("absolute" = rS, "relative" = rS_rel)
    return(out)
}


ReadPlot <- ReadStats_plot(ReadStats, count_mat = count_mat_raw)
ReadPlot_exonic <- ReadStats_plot_exonic(count_mat = count_mat_raw, fData = fData_raw, categories = 10)


pdf(file   =    file.path(figureDir, "ReadStats.pdf"),
    width  = 20,
    height = 6)
ReadPlot
dev.off()


pdf(file   =    file.path(figureDir, "ReadStats_uniqMapped.pdf"),
    width  = 30,
    height = 6)
ReadPlot_exonic
dev.off()

print(ReadPlot)


```



```{r DESeq2_setup}
dds <- DESeqDataSetFromMatrix(colData = pData,   # dataset HTS-Seq, with associated conditions
                              countData = count_mat_raw,
                              design= ~Donor + condition)

keep <- rowSums(counts(dds)) >= 10  # discard genes with less than 10 reads: low quality filtering
dds <- dds[keep,]
dds <- DESeq(dds, betaPrior = FALSE, test="LRT",reduced = ~ 1)
rld <- rlog(dds, blind=TRUE)

dds_out <- list()

topTables <- list()
topTables$fullModel <- results(dds)

dds_fresh <- DESeqDataSetFromMatrix(colData = pData[pData$Culture == "Fresh",],   
                    countData = count_mat_raw[,pData[pData$Culture == "Fresh",]$sample_name],
                              design= ~condition + Donor)

keep_fresh <- rowSums(counts(dds_fresh)) >= 10  # discard genes with less than 10 reads: low quality filtering
dds_fresh <- dds_fresh[keep_fresh,]
dds_fresh <- DESeq(dds_fresh, betaPrior = FALSE, test="LRT",reduced = ~ 1)


topTables$fullModel_fresh <- results(dds_fresh)


pData_annot <- pData %>%
                dplyr::rename(Cell_type = `cell_type`) %>%
                column_to_rownames("sample_name")

eset_rld <- ExpressionSet(assayData = assay(rld),
                          phenoData = AnnotatedDataFrame(pData_annot))

```



```{r PVCA}

pvca_func <- function(eset, batch.factors, threshold, inter = T){
  require(lme4)
  pvca <- PVCA(exprs(eset), meta = pData(eset)[,batch.factors], threshold = threshold, inter= inter)
  #return(pvca)
  #return(pvca)
  df <-  as.data.frame(pvca) %>% 
          rownames_to_column("batch") %>%
          dplyr::rename(Prop_var = 2) %>%
          arrange(desc(Prop_var))
  print(df)
  p <- ggplot(df, aes(x = reorder(batch,Prop_var), y = Prop_var)) +
    geom_bar(stat = "identity") +
    labs(x = "Condition",
         y = "Weighted average proportion variance") +
    theme_bw() +
    coord_flip()
  out <- list("results" = df, "plot" = p)
  return(out)
}

#Perform PVCA on all samples
pvca_all <- pvca_func(eset_rld,batch.factors = c("Cell_type", "Culture"), threshold = 0.1, inter = F )


pvca_all

```


```{r sample_correlation}
rld_cor <- cor(exprs(eset_rld))


heat.colors <- brewer.pal(50, "Blues")


rld_corr_hm <- pheatmap(rld_cor,
                        color = heat.colors,
                        #annotation_row = pData(eset_rld)[c("condition", "Cell_type", "Mouse_strain")],
                        annotation_col = pData(eset_rld)[c("Culture",  "Cell_type", "Donor")],
                        treeheight_row = 10,
                        treeheight_col = 20,
                        filename = "output/figures/correlation_heatmap_human.pdf")
```



```{r PCA}


dds_to_eset <- function(dds, fData = NULL){
  if(!is.null(fData)){
    eset <- ExpressionSet(assayData = assay(dds),
                          phenoData = AnnotatedDataFrame(as.data.frame(colData(dds))),
                          featureData = AnnotatedDataFrame(fData))
  } else{
     eset <- ExpressionSet(assayData = assay(dds),
                          phenoData = AnnotatedDataFrame(as.data.frame(colData(dds))))
  }
 
  return(eset)
  
}

pca_func <- function(object, scale = T, ntop = NULL){
  if(class(object) ==  "DESeqTransform"){
    eset <- dds_to_eset(object)
  } else if(class(object) == "ExpressionSet"){
    eset <- object
  } else {
    stop("Invalid object.")
  }
  
  if(!is.null(ntop)){
    rv <- rowVars(exprs(eset))
    select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
          length(rv)))]
    mat <- t(exprs(eset)[select,])
   
  } else {
      mat <- t(exprs(eset))
  }
  
  pca <- summary(prcomp(mat, scale. = scale))
  
  importance <- pca$importance 
  importance_df <- t(importance) %>%
                    as.data.frame() %>%
                    rownames_to_column("PC") 
  
  elbow <- findElbowPoint(importance_df$`Standard deviation`^2)
  #elbow <- colnames(importance)[findElbowPoint(importance_df$`Standard deviation`^2)]
  
  #elbowPC <- colnames(importance)[]
  
  holm <- parallelPCA(mat)$n
  
  scree <- ggplot(importance_df, aes(x = reorder(PC,-`Proportion of Variance`) , y = `Proportion of Variance` )) + 
            geom_bar(stat = "identity") +
            geom_point(data = importance_df, aes(x = reorder(PC,-`Proportion of Variance`), 
                                                 y = `Cumulative Proportion`),
                       size = 0.5) +
            stat_smooth(data = importance_df, aes(x = reorder(PC,-`Proportion of Variance`), 
                                                 y = `Cumulative Proportion`), method = "loess") + 
            #geom_smooth(data = importance_df, aes)
            geom_vline(xintercept =  elbow, linetype = "dashed") + 
            geom_vline(xintercept =  holm, linetype = "dashed") + 
            geom_text(aes(elbow - 2, 0.75, label = "Elbow", vjust = -1)) + 
            geom_text(aes(holm + 2, 0.75, label = "Holm", vjust = -1)) + 
            theme_bw() +
            theme(axis.text.x = element_text(angle = 90 ))
  
  

  pca_df <- pca$x %>%
            as.data.frame() %>%
            rownames_to_column("SampleID") %>%
            inner_join(., pData(eset) %>% rownames_to_column("SampleID"), by  = "SampleID") %>%
            dplyr::select(colnames(pca$x), SampleID, everything())
  
  out <- list("pca_df" = pca_df, "importance" = importance, "scree" = scree, "loadings" = pca$rotation)

  return(out)
}

#aes_string(color = color, fill = fill, shape = shape, size = size)
pca_plot_func <- function(pca_object, dims = c(1:2), color = NULL,  fill = NULL,  shape = NULL, size = 3, geom_size = 0.5,
                          color_vector = NULL, fill_vector = NULL, shape_vector = NULL, size_limits = NULL){
    dim_len <- seq(dims)
    combn_dims <- combn(dim_len, m = 2, simplify = F)
    importance <- as.data.frame(pca_object$importance)
    
    out <- lapply(combn_dims, function(x){
      var1 <- colnames(pca_object$pca_df)[x[1]]
      var2 <- colnames(pca_object$pca_df)[x[2]]
      p <- ggplot(pca_object$pca_df, aes_string(x = var1, y = var2)) 
      if(is.numeric(size)) {
        p <- p + geom_point(aes_string(color = color, fill = fill, shape = shape), size = size)
      } else {
      p <- p + geom_point(size = geom_size, aes_string(color = color, fill = fill, shape = shape))
      }
      p <- p + 
            theme_bw() + 
            xlab(label = paste(var1 ,  " (", signif(importance[[var1]][2] *100, 4), "%) ", sep = "")) +
            ylab(label = paste(var2 ,  " (", signif(importance[[var2]][2] *100, 4), "%) ", sep = "")) 

      if(!is.null(fill_vector)){
      p <- p + scale_fill_manual(values = fill_vector)
      }
      if(!is.null(color_vector)){
      p <- p + scale_color_manual(values = color_vector)
      }
      if(!is.null(shape_vector)){
      p <- p + scale_shape_manual(values = shape_vector) +
                guides(fill = guide_legend(override.aes=list(shape=21)))
      }
      if(!is.null(size_limits)){
      p <- p + scale_size_continuous(limits = size_limits)
      }
      return(p)
    })
    
  
    
}


pca_pairplot <- function(pca_object, dims = c(1:3), color  = "condition" ){
  
  pca_df <- pca_object$pca_df
  p <- ggpairs(data = pca_df, columns = dims, aes_string(colour = color), 
             showStrips = F,
             upper = list(continuous = "blank", combo = "blank"),
             lower = list(combo = wrap("box_no_facet", alpha=1), continous = "points"),
             diag = list(discrete = "blankDiag"),
             legend = 1,
             cardinality_threshold = length(unique(pca_df[[color]])),
             switch = "y") +
             theme_bw()
  return(p)
  
}

loadingScorePlot <- function(pca_object, dims = c(1:3), fData, pct.filt = 0.0005, top = NULL, loadSelect = "all"){
  pc_select <- colnames(pca_object$loadings)[dims]
  df <- pca_object$loadings %>%
        as.data.frame() %>%
        rownames_to_column("GeneID") %>%
        gather(PC, value, -GeneID ) %>%
        filter(PC %in% pc_select) %>%
        mutate(PC = factor(PC, levels = pc_select))  %>%
        inner_join(., fData %>% rownames_to_column("GeneID"), by = "GeneID") #%>%
         #
  
  if(loadSelect == "all"){
    df <- df %>% 
         group_by(PC) %>%
         mutate(abs_load = abs(value)) %>%
         mutate(rank = rank(-abs_load)) %>%
         mutate(quantile = ntile(abs_load, n = 1000)) %>%
         ungroup() 
  } else if(loadSelect == "pos"){
     df <- df %>% 
         filter(value > 0) %>%
         group_by(PC) %>%
         mutate(load = value) %>%
         mutate(rank = rank(-load)) %>%
         mutate(quantile = ntile(load, n = 1000)) %>%
         ungroup() 
  } else if(loadSelect == "neg"){
     df <- df %>% 
         filter(value < 0) %>%
         group_by(PC) %>%
         mutate(load = value) %>%
         mutate(rank = rank(load)) %>%
         mutate(quantile = ntile(-load, n = 1000)) %>%
         ungroup() 
  }

  if(!is.null(top)){
    df_filt <- df %>% filter(rank <= top)
  } else {
    df_filt <-  df %>% filter(quantile >= (1-pct.filt) * 1000)
  }
  
  p <- ggplot(df_filt, aes(x = PC, y = load, color = load ) ) + 
        geom_point(size = 3) + 
        geom_label_repel(aes(label = Gene)) + 
        theme_bw()
  out <- list("plot" = p, "topFeatures" = split(df_filt, f  = df_filt$PC))
  return(out)
}


```


```{r run PCA}

pca_all <- pca_func(eset_rld)
pca_all_plot <- pca_plot_func(pca_all, color = "Cell_type", shape = "Culture", size = 3)

#test2 <- summary(test)



pdf(file = file.path(figureDir, "PCA_all_samples.pdf"),width = 8)
pca_all_plot[[1]] +
         ggtitle('PCA All Samples' )
dev.off()


cultured_samples <- pData(eset_rld) %>%
                rownames_to_column("SampleID") %>%
                split(., f = .$Culture)
            

eset_fresh <- eset_rld[,cultured_samples$Fresh$SampleID]
pvca_fresh <- pvca_func(eset_fresh,batch.factors = c("Cell_type", "Donor"), threshold = 0.1, inter = F )

fresh_corr <- sva::ComBat(exprs(eset_fresh), batch = pData(eset_fresh)$Donor, mod = model.matrix(~ condition, data = pData(eset_fresh)))
eset_fresh_corr <- eset_fresh
exprs(eset_fresh_corr) <- fresh_corr

pca_fresh <- pca_func(eset_fresh_corr )
pdf(file = file.path(figureDir, "PCA/PCA_fresh_samples.pdf"),width = 8)
print(pca_plot_func(pca_object = pca_fresh, color = "Cell_type", shape = "Donor", size= 4 ))
dev.off()

pca_fresh_top1000 <- pca_func(eset_fresh_corr, ntop = 1000)
pdf(file = file.path(figureDir, "PCA/PCA_Fresh_samples_top1000.pdf"),width = 8)
pca_plot(pca_object = pca_fresh_top1000, color = "Cell_type", shape = "Donor", size= 4 )
dev.off()

pca_fresh1000_out <- as.data.frame(pca_fresh_top1000$loadings) %>%
                      rownames_to_column("SYMBOL") %>%
                      rowid_to_column("rowid") %>%
                      dplyr::select("SYMBOL","PC1", "PC2", "rowid")

write_csv(pca_fresh1000_out, file = "output/data/PCA_fresh_loadings.csv" )

culture_samples <- pData(eset_rld) %>%
                rownames_to_column("SampleID") %>%
                filter(Culture == "Culture") %>%
                .$SampleID

eset_culture <- eset_rld[,cultured_samples$Culture$SampleID]
pvca_culture <- pvca_func(eset_culture,batch.factors = c("Cell_type", "Donor"), threshold = 0.1, inter = F )

culture_corr <- sva::ComBat(exprs(eset_culture), batch = pData(eset_culture)$Donor, mod = model.matrix(~ condition, data = pData(eset_culture)))
eset_culture_corr <- eset_culture
exprs(eset_culture_corr) <- culture_corr


pca_culture <- pca_func(eset_culture_corr)
pdf(file = file.path(figureDir, "PCA/PCA_Culture_samples.pdf"),width = 8)
pca_plot(pca_object = pca_culture, color = "Cell_type", shape = "Donor", size= 4 )
dev.off()

pca_culture_top1000 <- pca_func(eset_culture_corr, ntop = 1000)
pdf(file = file.path(figureDir, "PCA/PCA_Culture_samples_top1000.pdf"),width = 8)
pca_plot(pca_object = pca_culture_top1000, color = "Cell_type", shape = "Donor", size= 4 )
dev.off()



rld_corr <- sva::ComBat(exprs(eset_rld), batch = pData(eset_rld)$Donor, mod = model.matrix(~ condition, data = pData(eset_rld)))
eset_rld_corr <- eset_rld
exprs(eset_rld_corr) <- rld_corr

pca_all_corr <- pca_func(eset_rld_corr )
pdf(file = file.path(figureDir, "PCA/PCA_all_corrected_samples.pdf"),width = 8)
print(pca_plot_func(pca_object = pca_all_corr, color = "condition", shape = "Donor", size= 4 ))
dev.off()




```



```{r full model_hm}

full_genes <- topTables$fullModel  %>%
                as.data.frame() %>%
                rownames_to_column("GeneID") %>%
                #inner_join(., fData_raw %>% rownames_to_column("GeneID"), by ="GeneID") %>%
                filter(padj < 0.05)
full_genes_fresh <- topTables$fullModel_fresh  %>%
                as.data.frame() %>%
                rownames_to_column("GeneID") %>%
                #inner_join(., fData_raw %>% rownames_to_column("GeneID"), by ="GeneID") %>%
                filter(padj < 0.05)


colorAssign <- function(valueVector, scale_limits = NULL, colors = c("blue", "white", "red"), length.vector = 500){
  colorLS <- colorRampPalette(colors = colors)(length.vector)  
  if(is.null(scale_limits)){
    breaks <- seq(-max(abs(valueVector)), max(abs(valueVector)), length.out = length.vector)
  } else {
    breaks <- seq(scale_limits[1], scale_limits[2], length.out = length.vector)
  }
  
  
  minBreak <- which(abs(breaks - min(valueVector)) == min(abs(breaks - min(valueVector))))
  maxBreak <- which(abs(breaks - max(valueVector)) == min(abs(breaks - max(valueVector))))
  return(colorLS[minBreak:maxBreak])
}

# test <- seq(-3,5, length.out =  100)
# test2 <- colorAssign(valueVector = test)


DEG_heatmap <- function(eset, heatmap_attributes = NULL, colors = c("blue", "white", "red"), scale = T){
    if(scale){
       mat_scaled <- t(scale(t(exprs(eset)), center = T, scale = T))
       colorLS <- colorAssign(colors = colors, valueVector = mat_scaled)
    } else {
      mat_scaled <- exprs(eset)
      colorLS <- colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100)
    }
   
  
    params <- list(mat = mat_scaled,
                   scale = "none",
                   color = colorLS,
                   clustering_method  = "ward.D2")
    
    
    if(!is.null(heatmap_attributes)){
      params <- modifyList(params, heatmap_attributes, keep.null = T)
    }

    p <- do.call("pheatmap", params)            
                   
    return(p)
    # p <- pheatmap(mat = exprs(eset),
    #               )
  
}


full_DEG <- DEG_heatmap(eset_rld[full_genes$GeneID,], 
                    heatmap_attributes = list(annotation_col = pData(eset_rld)[c("Culture", "Donor",
                                                                                 "Cell_type")],
                                              show_rownames = F,
                                              show_colnames = F,
                                              main = "human_subsets_DEG",
                                              filename = file.path(figureDir, "full human_subsets_DEG.pdf")) )


fresh_DEG <- DEG_heatmap(eset_fresh_corr[full_genes_fresh$GeneID,], 
                    heatmap_attributes = list(annotation_col = pData(eset_fresh_corr[full_genes_fresh$GeneID,])[c("Cell_type")],
                                              show_rownames = F,
                                              show_colnames = F,
                                              clustering_method = "ward.D2",
                                              cutree_cols = 4,
                                              annotation_colors = annotation_colors["Cell_type"],
                                              main = "fresh human_subsets_DEG",
                                              name = "Z-Score") )
pdf(file.path(figureDir, "fresh human_subsets_DEG.pdf"))
fresh_DEG
dev.off()

marker_genes <- c( "CD3D", "CD4", "CD8B", "ITGAX", "ITGAM", "CD19")




marker_gene_hm <- DEG_heatmap(eset_rld[marker_genes,],
                    scale = F,
                    heatmap_attributes = list(annotation_col = pData(eset_rld)[c("Culture", "Donor",
                                                                                 "Cell_type")],
                                              show_rownames = T,
                                              #labels_row = marker_genes_df$Gene,
                                              cellheight = 8,
                                              cellwidth = 5, 
                                              fontsize = 6,
                                              height = 6,
                                              filename = file.path(figureDir, "marker_gene_heatmap.pdf")) )





```



```{r contrast lists}

condition_levels <- list("Culture" = relevel(factor(unique(pData(eset_rld)$Culture)),
                                             ref = "Fresh"),
                         "Cell_type" = factor(unique(pData(eset_rld)$Cell_type), 
                                              levels = c("CD4", "CD8", "gd", "DNT")))



cell_comp <- unlist(lapply(combn(rev(levels(condition_levels$Cell_type)), m = 2, simplify = F),
                           function(x){
      int <- lapply(levels(condition_levels$Culture), function(y){
       
          cont <- paste("condition", paste(x[1], "__", y, sep = ""),
                      paste(x[2], "__", y, sep = ""), sep = "!")
        return(cont)
      })
      return(int)
}))

culture_comp <- unlist(lapply(levels(condition_levels$Cell_type), function(x){
      
        #CellCulture <- paste(x, y, sep = "_")
        cont <- paste("condition", paste(x, levels(condition_levels$Culture)[2],sep = "__"),
                      paste(x, levels(condition_levels$Culture)[1], sep = "__"), sep = "!")
 
      
      return(cont)
}))

```


```{r diff_expr }
deseq_analysis <- function(deseqObj, contrast_name, contrast_group, ctrl_group, rldcheck= TRUE){
  dds <- deseqObj
  keep <- rowSums(counts(dds)) >= 10  # discard genes with less than 10 reads: low quality filtering
  dds <- dds[keep,]
  dds$condition <- relevel(dds$condition, ref = ctrl_group)  # group low defined as the control here.
  dds <- DESeq(dds, test = "Wald")
  
  out <- list()
  if(rldcheck == TRUE){
    out$rld <- rlog(dds, blind=FALSE) #Regularized Log transformation of the data for clustering (PCA, heatmap)
  }
  out$res <- results(dds,contrast=c("condition",contrast_group,ctrl_group))
  coefN <- which(resultsNames(dds) == paste("condition_",contrast_group, "_vs_", ctrl_group, sep = "" ))
  #res_LFC <- lfcShrink(dds, contrast=c("condition",contrast_group,ctrl_group), type = "apeglm")
  res_LFC <- lfcShrink(dds, coef = coefN, type = "apeglm")
  out$res_LFC <- res_LFC[!is.na(res_LFC$padj),]
  out$contrastVar <- contrast_name
  out$contrastGroups <- c(contrast_group,ctrl_group)
  out$sampleIDs <- colnames(dds[,colData(dds)[[contrast_name]] %in% c(contrast_group,ctrl_group)])
  return(out)
}  





topTables_contrasts <- list()
#dds_contrast <- DESeq(dds, test = "Wald")
for(i in c(cell_comp, culture_comp)){
    split_con <- unlist(str_split(i, pattern = "!"))
    contrastName <- paste(split_con[2], split_con[3], sep = "_vs_")
    print(split_con)
    topTables_contrasts[[contrastName]] <- deseq_analysis(dds, 
                                                          contrast_name = split_con[1],
                                                          contrast_group = split_con[2],
                                                          ctrl_group = split_con[3],
                                                          rldcheck = F)
}

annotation_colors <- list("Culture"= c("Fresh" = "#63D6DE", "Culture" = "#A2C93E"),
                          "Cell_type"  = c("CD4" = "#f8766d", "CD8" =  "#7cae00",
                                           "DNT" = "#00bfc4", "gd" = "#c77cff"),
                          "Donor" =  c("924"  = "#59C1F9", "937" = "#F0978D", "938" = "gray"))



test <- lapply(names(topTables_contrasts), function(x){
  top <- topTables_contrasts[[x]] 
  #return(top)
  genes <- top$res_LFC %>%
            as.data.frame() %>%
            rownames_to_column("gene") %>%
            filter(!is.na(padj) ) %>%
            filter(padj < 0.05) %>%
            filter(abs(log2FoldChange) > 1.25) %>%
            .$gene

  
  samples <- top$sampleIDs
  
  eset_filt <- eset_rld[genes,samples]
  filename <-  paste("output/figures/DEG_heatmaps/", x,".pdf", sep ="")
  hm <- DEG_heatmap(eset_filt, 
                    heatmap_attributes = list(annotation_col = pData(eset_rld)[c("Culture",
                                                                            "Donor", "Cell_type")],
                                              show_rownames = T, 
                                              filename = filename,
                                               annotation_colors = annotation_colors))
})

```


```{r DNT expression}

DNT_cont <- names(topTables_contrasts)[grepl("DNT", names(topTables_contrasts))]
DNT_cont_fresh <- DNT_cont[!grepl("Culture", DNT_cont)]
DNT_cont_culture <- DNT_cont[!grepl("Fresh", DNT_cont)]
DNT_cross_culture <- DNT_cont[grepl("Fresh", DNT_cont) & grepl("Culture", DNT_cont)]
cross_culture <- names(topTables_contrasts)[grepl("Fresh", names(topTables_contrasts)) &
                                             grepl("Culture", names(topTables_contrasts)) ]

DNT_markers_fresh <- do.call('rbind', lapply(DNT_cont_fresh, function(x){
                  df <- topTables_contrasts[[x]]$res_LFC %>%
                        as.data.frame() %>%
                        rownames_to_column('GeneID') %>%
                        filter(padj < 0.05) %>%
                        #filter(log2FoldChange > 0) %>%
                        #dplyr::select(GeneID) %>%
                        mutate(contrast = x)
                  return(df)
                

})) %>%
  #group_by(GeneID) %>%
  mutate(dir = sign(log2FoldChange)) %>%
  group_by(dir, GeneID) %>%
  #mutate(n_dir  = n_distinct())
  mutate(n_conditions = n_distinct(contrast)) %>%
  ungroup() %>%
  filter(n_conditions == 3) %>%
  dplyr::select(-contrast) %>%
  .$GeneID %>%
    unique() 






```


```{r TF_genes}
# top
# 
# names(gmt_list$c5)[grepl("DNA_BINDING_TRANSCRIPTION_FACTOR_ACTIVITY",
#                          names(gmt_list$c5))]
# 
# 
ensembl <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
symbolConv <- getBM(attributes= c("ensembl_gene_id","hgnc_symbol", "description", "go_id"),
                      filters = 'hgnc_symbol', values =row.names(eset_rld), mart = ensembl)

# 
# 
# tf_genes <- unique(symbolConv[symbolConv$go_id == 'GO:0003700',]$hgnc_symbol)
cytok_chemok_genes <- unique(symbolConv[symbolConv$go_id %in% c('GO:0008009',
                                                                'GO:0005125'),]$hgnc_symbol)
cytok_chemok_receptor_genes <- unique(symbolConv[symbolConv$go_id %in% c('GO:0004950',
                                                                'GO:0004896'),]$hgnc_symbol)
# 
# fresh_DEG_TF <- DEG_heatmap(eset_rld[full_genes_fresh$GeneID, 
#                                   pData[pData$Culture == "Fresh",]$sample_name], 
#                     heatmap_attributes = list(annotation_col = pData(eset_rld)[c("Culture", "Donor", "Cell_type")],
#                                               show_rownames = F,
#                                               show_colnames = F,
#                                               main = "fresh human_subsets_DEG",
#                                               filename = file.path(figureDir, "fresh human_subsets_DEG.pdf")) )
#   
# 
# fresh_DEG_DNT_markers <- DEG_heatmap(eset_rld[DNT_markers_fresh, 
#                                   pData[pData$Culture == "Fresh",]$sample_name], 
#                     heatmap_attributes = list(annotation_col = pData(eset_rld)[c("Culture", "Donor", "Cell_type")],
#                                               show_rownames = F,
#                                               show_colnames = F,
#                                               main = "DNT human_subsets_DEG_marker",
#                                               filename = file.path(figureDir, "fresh human_subsets_DEG_DNT_marker.pdf")) )


```


```{r }
# lapply("TF")
# DNT_markers_fresh_single <- do.call("rbind", lapply(DNT_cont_fresh,  function(x){
#     df <- topTables_contrasts[[x]]$res_LFC %>%
#           as.data.frame() %>%
#           rownames_to_column("GeneID") %>%
#           filter(pvalue < 0.05) %>%
#           filter(log2FoldChange > 0) %>%
#           mutate(contrast = x)
#       
#      return(df)     
# }))
# 
# writexl::write_xlsx(DNT_markers_fresh_single %>% filter(GeneID %in% tf_genes) %>%
#                       split(., f = .$contrast), 
#                     path = file.path(dataDir, "TF_fresh DNT genes.xlsx"))
# 
# writexl::write_xlsx(DNT_markers_fresh_single %>% filter(GeneID %in% cytok_chemok_genes) %>%
#                       split(., f = .$contrast), 
#                     path = file.path(dataDir, "Cytokine and chonekine_fresh DNT genes.xlsx"))
# 
# writexl::write_xlsx(DNT_markers_fresh_single %>% filter(GeneID %in% cytok_chemok_receptor_genes) %>%
#                       split(., f = .$contrast), 
#                     path = file.path(dataDir, "Cytokine and chonekine_receptor_fresh DNT genes.xlsx"))
# 
# 
# 
# DNT_markers_Culture_single <- do.call("rbind", lapply(DNT_cont_culture,  function(x){
#     df <- topTables_contrasts[[x]]$res_LFC %>%
#           as.data.frame() %>%
#           rownames_to_column("GeneID") %>%
#           filter(pvalue < 0.05) %>%
#           filter(log2FoldChange > 0) %>%
#           mutate(contrast = x)
#       
#      return(df)     
# }))
# 
# 
# writexl::write_xlsx(DNT_markers_Culture_single %>% filter(GeneID %in% tf_genes) %>%
#                       split(., f = .$contrast), 
#                     path = file.path(dataDir, "TF_culture DNT genes.xlsx"))
# 
# writexl::write_xlsx(DNT_markers_Culture_single %>% filter(GeneID %in% cytok_chemok_genes) %>%
#                       split(., f = .$contrast), 
#                     path = file.path(dataDir, "Cytokine and chemokine_culture DNT genes.xlsx"))
# 
# writexl::write_xlsx(DNT_markers_Culture_single %>% filter(GeneID %in% cytok_chemok_receptor_genes) %>%
#                       split(., f = .$contrast), 
#                     path = file.path(dataDir, "Cytokine and chemokine_receptor_culture DNT genes.xlsx"))
# 
# 
# 
# 
# cross_culture_markers_single <- do.call("rbind", lapply(cross_culture,  function(x){
#     df <- topTables_contrasts[[x]]$res_LFC %>%
#           as.data.frame() %>%
#           rownames_to_column("GeneID") %>%
#           filter(pvalue < 0.05) %>%
#           filter(log2FoldChange > 0) %>%
#           mutate(contrast = x)
#       
#      return(df)     
# }))
# 
# 
# writexl::write_xlsx(cross_culture_markers_single %>% filter(GeneID %in% tf_genes) %>%
#                       split(., f = .$contrast), 
#                     path = file.path(dataDir, "TF_culture-induced genes.xlsx"))
# 
# writexl::write_xlsx(cross_culture_markers_single %>% filter(GeneID %in% cytok_chemok_genes) %>%
#                       split(., f = .$contrast), 
#                     path = file.path(dataDir, "Cytokine and chemokine_culture-induced genes.xlsx"))
# 
# writexl::write_xlsx(cross_culture_markers_single %>% filter(GeneID %in% cytok_chemok_receptor_genes) %>%
#                       split(., f = .$contrast), 
#                     path = file.path(dataDir, "Cytokine and chemokine_receptor_culture-induced genes.xlsx"))


```



```{r fgsea_functions}


# 
# fgsea_function <- function(x,gmtfile, method = "shLFC", p_thr = 0.05, n.perm = 10000, maxSize = 5000, minSize = 15) {
#   ###function to do preranked geneset enrichment using fgsea using a given 1.srunken deseq input and 2.gmt file path
#   if(!method %in% c("shLFC","logp", "regression")){
#     stop("Invalid method for fgsea_function. Options are 'shLFC' or 'logp'")
#   }
#   shrunk_deseq_output <- x
#   shrunk_deseq_output <- shrunk_deseq_output[!is.na(shrunk_deseq_output$padj),]
#   if( method == "shLFC"){
#       #shrunk_deseq_output <- shrunk_deseq_output[order(-shrunk_deseq_output$log2FoldChange),] 
#       #ranks <- shrunk_deseq_output
#       ranks_set <- setNames(shrunk_deseq_output$log2FoldChange, row.names(shrunk_deseq_output))
#   } else if(method == "logp") {
#       shrunk_deseq_output$rank_metric <- sign(shrunk_deseq_output$log2FoldChange) *   -log(shrunk_deseq_output$pvalue)
#       shrunk_deseq_output <- shrunk_deseq_output[order(-shrunk_deseq_output$rank_metric),] 
#       ranks <- shrunk_deseq_output
#       ranks_set <- setNames(ranks$rank_metric, row.names(ranks))
#   } else if(method == "regression") {
#     shrunk_deseq_output$rank_metric <- sign(shrunk_deseq_output$log2FoldChange) *   -log(shrunk_deseq_output$pvalue)
#       shrunk_deseq_output <- shrunk_deseq_output[order(-shrunk_deseq_output$rank_metric),] 
#       ranks <- shrunk_deseq_output
#       ranks_set <- setNames(ranks$rank_metric, row.names(ranks))
#   }
#   pathways <- gmtPathways(gmtfile)
#   fgseaRes<-fgsea(pathways,ranks_set,minSize=minSize,maxSize=maxSize,nperm=n.perm)
#   fgseaRes<- fgseaRes[fgseaRes$pval <=p_thr,]
#   fgseaRes<-fgseaRes[order(fgseaRes$padj),]
#   fgseaRes<-fgseaRes[!is.na(fgseaRes$padj),]
#   return(fgseaRes)
# }
# 
# fgsea_output <- function(fgsea_vector,
#                          eset_contrast,
#                          outcome,
#                          geneset_list,
#                          geneset,
#                          fileDir,
#                          method = "shLFC",
#                          p_thr = 0.05, 
#                          maxSize = 5000,
#                          minSize = 15) {
#   if(length(fgsea_vector[[outcome]]) == 0) {
#     fgsea_list <- list()
#   } else {
#     fgsea_list <- fgsea_vector[[outcome]]
#   }
#   fgsea_list[[geneset]]$geneset_file <- geneset_list[[geneset]]
#   fgsea_list[[geneset]]$output <- fgsea_function(eset_contrast, 
#                                                  geneset_list[[geneset]], 
#                                                  method = method, 
#                                                  p_thr = p_thr,
#                                                  maxSize = maxSize,
#                                                  minSize = minSize)
#   write.csv(as.data.frame(fgsea_list[[geneset]]$output[,c(1:7)]), 
#           file=file.path(fileDir,paste(outcome,geneset,method,"gsea.csv", sep="_")), 
#           quote = FALSE)
#   fgsea_vector[[outcome]] <- fgsea_list
#   return(fgsea_vector)
# }
# 
# 
# 
# 

```


```{r fgsea}

# 
# GSEA_data_Dir <- "output/data/gsea/"
# 
# 
# 
# fgsea_analysis <- list()
# 
# for(i in names(topTables_contrasts)){
#   for(j in names(geneset_list)) {
#     maxSize <- 500
#     minSize <- 15
#     if(j %in% c("CHEA", "transfac", "JASPER", "c3")){
#       maxSize <- 5000
#     } 
#     if(j %in% c("smpdb", "HMDB")){
#       minSize <- 5
#     }
#     topTable <- topTables_contrasts[[i]]$res_LFC
#                   
#                   
#     fgsea_analysis <- fgsea_output(fgsea_analysis,
#                                eset_contrast = topTable,
#                                outcome = i,
#                                geneset_list = geneset_list,
#                                geneset = j,
#                                fileDir = GSEA_data_Dir,
#                                p_thr = 0.1,
#                                method = "shLFC",
#                                minSize = minSize,
#                                maxSize = maxSize)
#     if(dim(fgsea_analysis[[i]][[j]]$output)[1] >0){
#       print(c(i,j,dim(fgsea_analysis[[i]][[j]]$output)[1]))
#     }
#   }
# }                     
# 
# lapply(names(fgsea_analysis), function(x){
#     
#     conditions <- str_split(x, pattern = "_vs_")[[1]]
#     conditions_split <- lapply(conditions, function(y){
#        splt <- str_split(y, pattern = "__")[[1]]
#        splt2 <- str_split(splt[1], pattern = "_")[[1]]
#        return(list("cell" = splt2[1], "Organ" = splt2[2], "Strain" = splt[2]))
#       
#     })
#     
#     if(conditions_split[[1]]$cell != conditions_split[[2]]$cell){
#       contrast_type <- "Cell_type_contrasts"
#     } else if(conditions_split[[1]]$Organ != conditions_split[[2]]$Organ){
#       contrast_type <- "Organ_contrasts"
#     }  else {
#       contrast_type <- "Strain_contrasts"
#     }
#     out <- sapply(names(fgsea_analysis[[x]]), USE.NAMES = T, simplify = F, function(y){
#           df <- fgsea_analysis[[x]][[y]]$output %>%
#                 mutate(gsColl = y,
#                          condition = x) %>%
#                   mutate(Enriched_in = ifelse(NES > 0, conditions[1], conditions[2])) %>%
#                   unnest(cols = leadingEdge) %>%
#                   group_by(pathway) %>%
#                   mutate(cLeadingEdge = paste(leadingEdge, collapse = ", ")) %>%
#                   ungroup() %>%
#                   dplyr::select(-leadingEdge) %>%
#                   unique() %>%
#                   dplyr::rename(leadingEdge = cLeadingEdge)
#         return(df)
#     })
#     filename <- paste("output/data/", contrast_type, "/GSEA_pathway_analysis/", x, "_GSEA.xlsx", sep = "")
#     print(filename)
#     writexl::write_xlsx(out, filename,format_headers = T)
#     top  <- topTables_contrasts[[x]]$res_LFC %>%
#             as.data.frame() %>%
#             rownames_to_column("MGI_symbol") %>%
#             mutate(Enriched_in = ifelse(log2FoldChange > 0, conditions[1], conditions[2])) %>%
#             mutate(Enriched_in = ifelse(pvalue > 0.05, "--", Enriched_in)) %>%
#             arrange(desc(-log(pvalue)))
#     
#     filename <- paste("output/data/", contrast_type, "/differential_expression/", x,
#                       "_differential_expression.xlsx", sep = "")
#     writexl::write_xlsx(top, filename,format_headers = T)
# })


```
